#include <iostream>
#include <Windows.h>


int seed = 0;

// fills buffer with random bytes generated by rand()
// this function assumes that enough space (`len`) is already allocated in `buf`
void fillBufferWithRandomBytes(char* buf, size_t len) {
	
	// DBG
	//memset(buf, 0x44, len); return;

	for (size_t i = 0; i < len; i++) {
		buf[i] = (char)rand();
	}
}

int setup() {
	// just using a static value for now
	// later on this should still be deterministic
	// to achieve repeatable results
	seed = 42;

	srand(seed);

	return 1;

}

void fuzz() {

  // Change `<CHANGEME>` to the respective pipe to fuzz
	LPCWSTR pipeName = L"\\\\localhost\\pipe\\\<CHANGEME>";
	HANDLE clientPipe = NULL;
	BOOL isPipeRead = true;
	//wchar_t message[MESSAGE_SIZE] = { 0 };
	DWORD bytesRead = 0;
	DWORD bytesWritten = 0;

	std::wcout << "Connecting to " << pipeName << std::endl;
	clientPipe = CreateFile(pipeName, GENERIC_READ | GENERIC_WRITE, 0, NULL, OPEN_EXISTING, 0, NULL);
	if (clientPipe == INVALID_HANDLE_VALUE) {
		std::wcout << "[!] Error opening pipe" << pipeName;
		return;
	}

	LPCVOID* dataptr = NULL;
  // reverse engineer the respective binary implementing the pipe server
  // and find out how much it reads max from the pipe
	dataptr = (LPCVOID*)malloc(0x1000);

	if (!dataptr) {
		std::wcout << "[!] Error allocating 0x1000 mem on the heap!" << std::endl;
		CloseHandle(clientPipe);
		return;
	}
	size_t nExecs = 0;
	while (1) {
    // again, 0x1000 comes from reverse engineering the respective pipe server
		fillBufferWithRandomBytes((char*)dataptr, 0x1000);
    // here we use modulo to send random num of bytes to the pipe
    // but max the value we got from reversing
		WriteFile(clientPipe, dataptr, rand() % 0x1001, &bytesWritten, 0);
		//std::wcout << "[*] Sent fuzz package...." << std::endl;
		//Sleep(1000);
		if (nExecs++ % 10 == 0) {
			std::wcout << "[*] Sent " << nExecs << " packets..." << std::endl;
		}
		if (nExecs % 1000 == 0) {
			// restart the fuzz function to setup the pipe again etc.
			break;
		}
	}

	CloseHandle(clientPipe);


}

int main()
{

	setup();
	while (1) {
		fuzz();
	}
	fuzz();

	/*
	while (isPipeRead) {
		isPipeRead = ReadFile(clientPipe, &message, MESSAGE_SIZE, &bytesRead, NULL);
		std::wcout << "Received message: " << message;
	}
	*/


	return 0;
}
